
const REACT_BACKEND_API = "https://bank-c.herokuapp.com";
const REACT_APP_GOOGLE_CLIENT_ID = "";
const REACT_APP_FACEBOOK_APP_ID = "";

export {
  REACT_BACKEND_API,
  REACT_APP_FACEBOOK_APP_ID,
  REACT_APP_GOOGLE_CLIENT_ID
}



